<?php

/**
 * Generate Markdown reference documentation from the generated SDK surface.
 *
 * Produces:
 *   - docs/api-reference.md   — every API group and its operations
 *   - docs/semantic-types.md  — every semantic value object and its constraints
 *
 * This is intentionally derived from the *generated* code (not the spec) so the docs
 * can never drift from what the SDK actually exposes.
 *
 * Usage: php scripts/generate-docs.php
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$apiDir = $root . '/generated/src/Api';
$semanticDir = $root . '/generated/semantic';
$docsDir = $root . '/docs';

if (!is_dir($docsDir) && !mkdir($docsDir, 0o755, true) && !is_dir($docsDir)) {
    fwrite(STDERR, "Cannot create docs/ directory\n");
    exit(1);
}

/**
 * @return list<string>
 */
function operations_of(string $file): array
{
    $text = (string) file_get_contents($file);
    $ops = [];
    if (preg_match_all('/public function (\w+)\(/', $text, $matches) === false) {
        return [];
    }
    foreach ($matches[1] as $name) {
        if (str_ends_with($name, 'WithHttpInfo')
            || str_ends_with($name, 'Async')
            || str_ends_with($name, 'AsyncWithHttpInfo')
            || str_ends_with($name, 'Request')
            || in_array($name, ['__construct', 'getConfig', 'getHostIndex', 'setHostIndex'], true)
        ) {
            continue;
        }
        $ops[$name] = true;
    }

    return array_keys($ops);
}

// ---------------------------------------------------------------------------
// API reference
// ---------------------------------------------------------------------------
$apiFiles = glob($apiDir . '/*.php') ?: [];
sort($apiFiles);

$api = "# API Reference\n\n";
$api .= "> Generated from the SDK surface by `scripts/generate-docs.php`. Do not edit by hand.\n\n";
$api .= "Every operation is reachable through the typed accessor:\n\n";
$api .= "```php\n\$api = \$client->api(\\Camunda\\Orchestration\\Api\\Api\\ProcessInstanceApi::class);\n```\n\n";

$totalOps = 0;
foreach ($apiFiles as $file) {
    $group = basename($file, '.php');
    $ops = operations_of($file);
    sort($ops);
    $totalOps += count($ops);
    $api .= "## {$group}\n\n";
    foreach ($ops as $op) {
        $api .= "- `{$op}()`\n";
    }
    $api .= "\n";
}

$header = "# API Reference\n\n";
$header .= sprintf(
    "> %d operations across %d API groups. Generated by `scripts/generate-docs.php`.\n\n",
    $totalOps,
    count($apiFiles),
);
$api = $header . substr($api, strlen("# API Reference\n\n"));

file_put_contents($docsDir . '/api-reference.md', $api);

// ---------------------------------------------------------------------------
// Semantic types
// ---------------------------------------------------------------------------
$semanticFiles = glob($semanticDir . '/*.php') ?: [];
sort($semanticFiles);

$sem = "# Semantic Types\n\n";
$sem .= "> Generated by `scripts/generate-docs.php`. Do not edit by hand.\n\n";
$sem .= "Each identifier is a distinct, self-validating value object in the ";
$sem .= "`Camunda\\Orchestration\\Semantic` namespace. All implement `Stringable` and ";
$sem .= "`JsonSerializable` and expose `::of()`, `->value()`, and `->equals()`.\n\n";
$sem .= "| Type | Pattern | Length | Description |\n";
$sem .= "| --- | --- | --- | --- |\n";

foreach ($semanticFiles as $file) {
    $name = basename($file, '.php');
    if ($name === 'SemanticKey') {
        continue;
    }
    $text = (string) file_get_contents($file);
    $pattern = preg_match("/public const PATTERN = '(.+?)';/", $text, $m) === 1 ? '`' . $m[1] . '`' : '—';
    $min = preg_match('/must be at least (\d+) character/', $text, $m) === 1 ? (int) $m[1] : null;
    $max = preg_match('/must be at most (\d+) character/', $text, $m) === 1 ? (int) $m[1] : null;
    $length = match (true) {
        $min !== null && $max !== null => "{$min}–{$max}",
        $max !== null => "≤ {$max}",
        $min !== null => "≥ {$min}",
        default => '—',
    };
    $desc = '';
    if (preg_match('/\/\*\*\s*\n\s*\*\s*(.+?)\s*\n/', $text, $m) === 1) {
        $desc = trim($m[1]);
    }
    $sem .= "| `{$name}` | {$pattern} | {$length} | {$desc} |\n";
}

file_put_contents($docsDir . '/semantic-types.md', $sem . "\n");

printf("Wrote docs/api-reference.md (%d operations) and docs/semantic-types.md\n", $totalOps);
